import {StyleSheet} from 'react-native';
import Colors from 'helpers/Colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'stretch',
    alignContent: 'space-between',
    //marginTop: 20,
    backgroundColor: 'transparent',
  },
  displayImage: {
    //top: 0,
    //left: 0,
    width: 132,
    height: 132,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    //position: "absolute",
  },
  displayButton: {
    //top: 0,
    //left: 0,
    width: 132,
    height: 132,
    backgroundColor: Colors.black, //'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    //position: "absolute",
  },
  displayName: {
    //top: 0,
    //left: 0,
    //width: 132,
    //height: 132,
    backgroundColor: 'transparent',
    //justifyContent: 'space-between',
    //alignItems: 'center',
    margin: 10,
    //paddingBottom: 30,

    //position: "absolute",-
  },
  userName: {
    fontSize: 24,
    textAlign: 'center',
    textAlignVertical: 'top',
    // fontWeight: 'normal',
    color: Colors.primaryText,
    fontFamily: 'AvenirNext-Bold',
  },
  logout: {
    fontSize: 12,
    textAlign: 'center',
    textAlignVertical: 'bottom',
    fontWeight: 'normal',
    color: Colors.darkGray,
  },
  profileHeader: {
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    margin: 20,
    backgroundColor: 'transparent',
    paddingTop: 10,
  },
  dataHeaders: {
    justifyContent: 'center',
    alignItems: 'flex-start',
    backgroundColor: Colors.white,
    padding: 10,
    paddingLeft: 20,
  },
  dataHeaderText: {
    fontFamily: 'AvenirNext-Bold',
    fontSize: 17,
    color: Colors.primaryText,
  },
  subUserName: {
    fontSize: 11,
    textAlign: 'center',
    color: Colors.inputTextColor,
    fontFamily: 'AvenirNext-Regular',
  },
  line: {
    backgroundColor: Colors.gray,
    marginTop: 2,
    height: 1,
    flexDirection: 'column',
    alignSelf: 'stretch',
    marginHorizontal: 31,
  },
  listButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    alignContent: 'stretch',
    paddingHorizontal: 31,
  },
  logout: {
    // paddingHorizontal: 31,
    marginHorizontal: 31,
    marginVertical: 37,
    alignSelf: 'stretch',
    // marginTop: 80,
    alignItems: 'center',
    backgroundColor: Colors.signupButton,
    borderRadius: 4,
  },
  headerPrimaryStyle: {
    color: '#606060',
    // opacity: 1,
    fontSize: 14,
    textAlign: 'left',
    fontFamily: 'AvenirNext-Regular',
  },
  headerSecondaryStyle: {
    color: '#C4C4C4',
    opacity: 1,
    fontSize: 11,
    textAlign: 'left',
    marginTop: 7,
    fontFamily: 'AvenirNext-Regular',
  },
  addCard: {
    color: '#606060',
    fontSize: 11,
    fontFamily: 'AvenirNext-Regular',
  },
  addCardContainer: {
    // margin: 10,
    // backgroundColor: 'yellow',
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 31,
    justifyContent: 'center',
  },
});

export default styles;
