export default {
  logo: 'RECEIPTZ',
  login: 'Login',
  signup: 'Sign Up',
  createAccount: 'Create Account',
  firstName: 'First Name',
  lastName: 'Last Name',
  loading: 'Loading',
  password: 'Password',
  email: 'Email',
  home: 'Home',
  homeMessage: 'Welcome',
  profile: 'Profile',
  profileMessage:
    'And this one has a nav, but with a different color than the login.',
  logout: 'Logout',
  settings: 'Settings',
  home: 'Receiptz',
  saved: 'Saved Receiptz',
};
